### ISSUE TITLE
Problem installing module

### ISSUE THREAD

**Issue by LordTyrius** [Magisk-Modules-Repo/adb-Installer#1]
I am unable to install this module using Magisk-Manager.
It processes the .zip but the module never shows up under installed modules, nor can I find the binaries in /system/xbin
I can provide additional information/logs, but I'm not sure what you need so please tell me what you need :)

**Comment by osm0sis** [comment]
Naturally a log of required.

I updated using Magisk Manager on my test device yesterday with no issues.

**Comment by LordTyrius** [comment]
Yeah, sorry for that, I was unsure _where_ to find the relevent information.
Here is a screenshot of the installation (seems flawless to me) and the magisk log after the reboot (no sign of this module)
![screenshot_20170810-171310](https://user-images.githubusercontent.com/16269108/29177943-63f3ca18-7df0-11e7-8225-ea58941c6101.png)
`--------- beginning of main
I(  455:  455) Magisk v13.3(1330) daemon started
I(  455:  457) ** post-fs mode running
--------- beginning of system
--------- beginning of crash
I(  455: 2419) ** post-fs-data mode running
I(  455: 2419) * Mounting /data/magisk.img
I(  455: 2419) * Running post-fs-data.d scripts
I(  455: 2419) * Loading modules
I(  455: 2419) Fdroid-Priv: constructing magic mount structure
I(  455: 2419) Greenify4Magisk: constructing magic mount structure
I(  455: 2419) * Mounting system/vendor mirrors
I(  455: 2419) mount: /dev/block/bootdevice/by-name/system -> /dev/magisk/mirror/system
I(  455: 2419) link: /dev/magisk/mirror/system/vendor -> /dev/magisk/mirror/vendor
I(  455: 2419) bind_mount: /system/priv-app
I(  455: 2419) bind_mount: /system/priv-app/Fdroid
I(  455: 2419) bind_mount: /system/priv-app/Greenify
I(  455: 2419) bind_mount: /system/priv-app/BackupRestoreConfirmation
I(  455: 2419) bind_mount: /system/priv-app/BlockedNumberProvider
I(  455: 2419) bind_mount: /system/priv-app/CNEService
I(  455: 2419) bind_mount: /system/priv-app/CalendarProvider
I(  455: 2419) bind_mount: /system/priv-app/CallLogBackup
I(  455: 2419) bind_mount: /system/priv-app/CarrierConfig
I(  455: 2419) bind_mount: /system/priv-app/ConfigUpdater
I(  455: 2419) bind_mount: /system/priv-app/Contacts
I(  455: 2419) bind_mount: /system/priv-app/ContactsProvider
I(  455: 2419) bind_mount: /system/priv-app/CtsShimPrivPrebuilt
I(  455: 2419) bind_mount: /system/priv-app/DefaultContainerService
I(  455: 2419) bind_mount: /system/priv-app/Dialer
I(  455: 2419) bind_mount: /system/priv-app/DocumentsUI
I(  455: 2419) bind_mount: /system/priv-app/DownloadProvider
I(  455: 2419) bind_mount: /system/priv-app/EmergencyInfo
I(  455: 2419) bind_mount: /system/priv-app/ExternalStorageProvider
I(  455: 2419) bind_mount: /system/priv-app/FusedLocation
I(  455: 2419) bind_mount: /system/priv-app/GmsCore
I(  455: 2419) bind_mount: /system/priv-app/GoogleBackupTransport
I(  455: 2419) bind_mount: /system/priv-app/GoogleExtServices
I(  455: 2419) bind_mount: /system/priv-app/GoogleFeedback
I(  455: 2419) bind_mount: /system/priv-app/GoogleLoginService
I(  455: 2419) bind_mount: /system/priv-app/GoogleOneTimeInitializer
I(  455: 2419) bind_mount: /system/priv-app/GooglePackageInstaller
I(  455: 2419) bind_mount: /system/priv-app/GooglePartnerSetup
I(  455: 2419) bind_mount: /system/priv-app/GoogleServicesFramework
I(  455: 2419) bind_mount: /system/priv-app/IFAAService
I(  455: 2419) bind_mount: /system/priv-app/InputDevices
I(  455: 2419) bind_mount: /system/priv-app/ManagedProvisioning
I(  455: 2419) bind_mount: /system/priv-app/MediaProvider
I(  455: 2419) bind_mount: /system/priv-app/MmsService
I(  455: 2419) bind_mount: /system/priv-app/MtpDocumentsProvider
I(  455: 2419) bind_mount: /system/priv-app/OPAppLocker
I(  455: 2419) bind_mount: /system/priv-app/OPCellBroadcastReceiver
I(  455: 2419) bind_mount: /system/priv-app/OPDeviceManager
I(  455: 2419) bind_mount: /system/priv-app/OPDeviceManagerProvider
I(  455: 2419) bind_mount: /system/priv-app/OPInCallUI
I(  455: 2419) bind_mount: /system/priv-app/OPMms
I(  455: 2419) bind_mount: /system/priv-app/OPNetworkSetting
I(  455: 2419) bind_mount: /system/priv-app/OPSettingsProvider
I(  455: 2419) bind_mount: /system/priv-app/OPSimContacts
I(  455: 2419) bind_mount: /system/priv-app/OPSystemUI
I(  455: 2419) bind_mount: /system/priv-app/OPWifiApSettings
I(  455: 2419) bind_mount: /system/priv-app/OnePlusCamera
I(  455: 2419) bind_mount: /system/priv-app/OnePlusCameraService
I(  455: 2419) bind_mount: /system/priv-app/OnePlusGallery
I(  455: 2419) bind_mount: /system/priv-app/OnePlusWizard
I(  455: 2419) bind_mount: /system/priv-app/Phonesky
I(  455: 2419) bind_mount: /system/priv-app/ProxyHandler
I(  455: 2419) bind_mount: /system/priv-app/QtiTetherService
I(  455: 2419) bind_mount: /system/priv-app/Settings
I(  455: 2419) bind_mount: /system/priv-app/SetupWizard
I(  455: 2419) bind_mount: /system/priv-app/SharedStorageBackup
I(  455: 2419) bind_mount: /system/priv-app/Shell
I(  455: 2419) bind_mount: /system/priv-app/SmartcardService
I(  455: 2419) bind_mount: /system/priv-app/StatementService
I(  455: 2419) bind_mount: /system/priv-app/StorageManager
I(  455: 2419) bind_mount: /system/priv-app/Tag
I(  455: 2419) bind_mount: /system/priv-app/TeleService
I(  455: 2419) bind_mount: /system/priv-app/Telecom
I(  455: 2419) bind_mount: /system/priv-app/TelephonyExtVodafonePack
I(  455: 2419) bind_mount: /system/priv-app/TelephonyProvider
I(  455: 2419) bind_mount: /system/priv-app/Velvet
I(  455: 2419) bind_mount: /system/priv-app/VpnDialogs
I(  455: 2419) bind_mount: /system/priv-app/WallpaperCropper
I(  455: 2419) bind_mount: /system/priv-app/com.qualcomm.location
I(  455: 2419) bind_mount: /system/priv-app/dpmserviceapp
I(  455: 2419) bind_mount: /system/priv-app/ltsmclient
I(  455: 2419) bind_mount: /system/priv-app/qcrilmsgtunnel
I(  455: 2419) bind_mount: /system/priv-app/softsim
I(  455: 2419) * Running module post-fs-data scripts
I(  455: 2442) * Starting MagiskHide
I(  455: 2442) hide_utils: Hiding sensitive props
I(  455: 2442) hide_list: [com.google.android.gms.unstable]
I(  455: 2442) hide_list: [com.snapchat.android]
I(  455: 2442) proc_monitor: init ns=mnt:[4026531840]
I(  455: 2585) ** late_start service mode running
I(  455: 2585) * Running service.d scripts
I(  455: 2585) * Running module service scripts
I(  455: 2442) proc_monitor: zygote ns=mnt:[4026534250] zygote64 ns=mnt:[4026534231]
I(  455: 2442) proc_monitor: com.google.android.gms.unstable (PID=5964 ns=mnt:[4026534300])
I( 5978: 5978) hide_utils: Re-linking /sbin
I(  455: 2442) proc_monitor: com.google.android.gms.unstable (PID=7872 ns=mnt:[4026534324])
`

**Comment by osm0sis** [comment]
You've got SuperSU leftovers, in particular /data/su.img, which is screwing up the target location detection. Clean your device and it'll work fine.

**Comment by LordTyrius** [comment]
Thanks for pointing me in the right direction. I thought using the supersu builtin cleanup feature and dirty flashing my rom /system was enough to get rid of it. I will report when I got this working :)

**Comment by osm0sis** [comment]
Use my unSU zip then flash your ROM's boot.img (extract from the ROM zip), then reflash Magisk.

**Comment by LordTyrius** [comment]
Can I flash boot.img from TWRP or do I have to use fastboot?

**Comment by LordTyrius** [comment]
Ok, that worked and the module is installed now. However I'm now failing SafetyNet checks, is that normal? Or is my /system wrong by flashing back and forth and a clean rom flash followed by this will result in a better state?

**Comment by osm0sis** [comment]
SafetyNet passes here. So it's unrelated to this module. Yes, I'd suggest you clean flash.

**Comment by LordTyrius** [comment]
Thanks for the help!
