### ISSUE TITLE
Device not appearing under adb devices

### ISSUE THREAD

**Issue by HeyItsJono** [Magisk-Modules-Repo/adb-Installer#2]
I managed to install this successfully on my phone (let's call it phone A), but when I plug it into phone B (phone B uses the OTG adaptor) and type `adb devices` into Phone A's Terminal Emulator, Phone A doesn't list Phone B, adb devices just returns nothing.

**Comment by osm0sis** [comment]
Sometimes it depends which end is plugged into which. Try switching the ends of the cord.

Can't guarantee it'll work for all devices either, but I've had no issues with my Nexus devices.

**Comment by osm0sis** [comment]
The other trick is to make sure adbd is running as root on the target device ("phone b"), with Terminal Emulator on the target phone `su -c "stop adbd; start adbd;"` :+1:

**Comment by HeyItsJono** [comment]
Sadly, that didn't work. `adb devices` still returns nothing. For reference, Phone B (the target device) is a rooted Google Pixel XL, and Phone A (host device) is a rooted Galaxy S4.

**Comment by osm0sis** [comment]
Might just be no luck from some Samsung-y stuff. Would likely work with Pixel as host and another device.
