### ISSUE TITLE
adb devices no devices?

### ISSUE THREAD

**Issue by klcb2010** [Magisk-Modules-Repo/adb-Installer#5]
Android Debug Bridge version 1.0.39
Revision android-8.0.0 arm
sagit:/data/data/com.termux/files/home #
adb devices
List of devices attached

sagit:/data/data/com.termux/files/home #

**Comment by osm0sis** [comment]
There is no useful information here, so it's an invalid issue.

Pleasea more detailed report of what you've tried on xda in my Odds and Ends thread and I'll try to help you.

**Comment by ecompton59** [comment]
probably need to cd if using termux
